/******************************
** NAME: AUTOMATED_NULL_AND_BLANK_STRING_REMOVAL.SQL   
** DESC: STORED PROCEDURE TO AUTONOMOUSLY PROCESS EACH FIELD OF A TABLE AND REMOVE 'NULL' AND ''.
** AUTH: HTTPS://GITHUB.COM/SANTAKRUSE
** DATE: 18/10/2017
**************************/

CREATE PROCEDURE AUTOMATED_NULL_AND_BLANK_STRING_REMOVAL(@TABLE NVARCHAR(100))
AS 
  BEGIN
    DECLARE @MAX_ID AS INT
    DECLARE @CURRENT_ID AS INT
    DECLARE @FIELD AS NVARCHAR(100)
    DECLARE @DAT_TYPE AS NVARCHAR(100)

    SET @MAX_ID = (SELECT MAX(ORDINAL_POSITION) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @TABLE)
    SET @CURRENT_ID = 1

    WHILE @CURRENT_ID <= @MAX_ID
      BEGIN
      SET @FIELD = (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @TABLE AND ORDINAL_POSITION = @CURRENT_ID)
      SET @DAT_TYPE = (SELECT DATA_TYPE FROM .INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @TABLE AND ORDINAL_POSITION = @CURRENT_ID)
      PRINT @DAT_TYPE 
      PRINT @FIELD
        IF @DAT_TYPE IN ('nvarchar', 'char', 'varchar', 'nchar')
          BEGIN
            EXEC('UPDATE ' + @TABLE + ' SET [' + @FIELD + '] = NULL WHERE [' + @FIELD + '] = '''' OR [' + @FIELD + '] = ''NULL''')
          END
      SET @CURRENT_ID = @CURRENT_ID + 1
      END
    END
  END
