/******************************
** NAME: AUTOMATED_CUSTOMISABLE_DATE_CREATED_DATE_UPDATED_USERNAME_TRIGGER.SQL   
** DESC: STORED PROCEDURE TO AUTONOMOUSLY ADD TRIGGER TO THE PROVIDED TABLE THAT FIRES WHEN RECORD IS UPDATED OR CREATED.
** AUTH: HTTPS://GITHUB.COM/SANTAKRUSE
** DATE: 25/01/2018
**************************/


CREATE PROC AUTOMATED_CUSTOMISABLE_DATE_CREATED_DATE_UPDATED_USERNAME_TRIGGER(
@TABLE VARCHAR(200)
)
AS BEGIN
	EXEC('
	CREATE TRIGGER Y2017_TRIGGER_ADD_CREATED_UPDATED_USERNAME_' + @TABLE +
	' ON ' + @TABLE +
	' AFTER UPDATE, INSERT
	AS BEGIN
		IF EXISTS(SELECT * FROM DELETED)
			BEGIN
				UPDATE TB
				SET DATE_UPDATED = GETDATE(), USERNAME = USER_NAME()
				FROM ' + @TABLE + ' TB
				WHERE TB.ID IN (SELECT ID FROM DELETED)
			END
		ELSE
			BEGIN
				IF EXISTS(SELECT * FROM INSERTED)
					BEGIN
						UPDATE TB
						SET DATE_CREATED = GETDATE(), USERNAME = USER_NAME()
						FROM ' + @TABLE + ' TB
						WHERE TB.ID IN (SELECT ID FROM INSERTED)
					END
			END		
	END')
END
